# Generated by Django 5.2.2 on 2025-06-09 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relacion_uno_muchos', '0002_dateexample_language_nullexample_simple_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DateExample',
        ),
        migrations.DeleteModel(
            name='NullExample',
        ),
        migrations.DeleteModel(
            name='Simple',
        ),
    ]
